In [ ]:
import json
import pandas as pd
import nltk
import sklearn.metrics
import pickle
import psycopg2
from yelpapi import YelpAPI
from pprint import pprint
from textblob import TextBlob
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score

//anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
with open('yelp_academic_dataset_review.json') as f:    
    d = [json.loads(f.readline().strip()) for x in range(100000)]

In [3]:
df = pd.DataFrame(d)

## Business IDs

In [4]:
len(df['business_id'].unique())

55117

In [78]:
df['business_id'].unique()

array([u'2aFiy99vNLklCx3T_tGS9A', u'2LfIuF3_sX6uwe-IR-P0jQ',
       u'0czfEgv9KAD4VlIa7ANPWQ', ..., u'-HVNYnMpPBIz_ZYiYj72Jg',
       u'3LrMazty_LrwDUhZCPX0uQ', u'-tLxryf1OpzVP9OSrznprg'], dtype=object)

In [102]:
bid = '-aaVZUYi4Ys_DP0rcBsFTg'
yelp_api = YelpAPI('fb-xs7dYOAKPmOWg2AKm6Q', 'kITuNYGqvYj5i66DFjng4eKlCsDZLPIdZTg2iXj0PxbmlLA8ESl9i3HGl2rKDTSg')
response = yelp_api.business_query(id=bid)

In [103]:
response['name']

u'Country Kitchen'

In [108]:
df_bid = df[df['business_id']==bid]

In [109]:
df_bid['polarity'] = [TextBlob(i).sentiment[0] for i in df_bid['text']]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [110]:
df_bid['subjectivity'] = [TextBlob(i).sentiment[1] for i in df_bid['text']]

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [115]:
df_bid

business_id  cool        date  funny               review_id  \
1834  -aaVZUYi4Ys_DP0rcBsFTg     1  2009-01-14      2  LzSa9K9JD3JxlToygKvIYQ   
1835  -aaVZUYi4Ys_DP0rcBsFTg     1  2012-09-30      0  FREza9bdzk73F9moTNmK4Q   
1836  -aaVZUYi4Ys_DP0rcBsFTg     0  2010-08-22      0  fUBOhUdJfyYBaKd_kd03nQ   
1837  -aaVZUYi4Ys_DP0rcBsFTg     2  2010-09-15      1  K0cwq7bms3gEulelnh12Gg   
1838  -aaVZUYi4Ys_DP0rcBsFTg     2  2011-02-28      1  _7TC__F2voaH4o_9Oybp9g   
1839  -aaVZUYi4Ys_DP0rcBsFTg     0  2012-12-04      0  DcQ6X-rMsnnRNNOEczPR9g   
1840  -aaVZUYi4Ys_DP0rcBsFTg     0  2010-12-16      1  b4H9hfRI6GFjnqrPDC7SqA   
1841  -aaVZUYi4Ys_DP0rcBsFTg     0  2010-01-03      0  i1oOi1uf7nKBYvAXRYswHA   
1842  -aaVZUYi4Ys_DP0rcBsFTg     1  2009-01-08      1  PyBoxmp1i_ve8y4HFY0SHA   
1843  -aaVZUYi4Ys_DP0rcBsFTg     0  2011-02-28      0  Y7fIn6BIQdgZnSj-5WnHlw   
1844  -aaVZUYi4Ys_DP0rcBsFTg     1  2008-10-15      0  ZCjZBNvyD6NqxjUH6wX2ZQ   
1845  -aaVZUYi4Ys_DP0rcBsFTg     0  2009-02-15      0  O017FcM9qGllmb00FHTxng   
1846  -aaVZUYi4Ys_DP0rcBsFTg     0  2012-03-02      0  2OiEl9BfEN27M5RX55F2ew   
1847  -aaVZUYi4Ys_DP0rcBsFTg     0  2012-03-15      0  IeQgvG45SYzhmlBKwY4azw   
1848  -aaVZUYi4Ys_DP0rcBsFTg     1  2009-01-14      0  acbHVSfioxCgLoGcNzZxDw   
1849  -aaVZUYi4Ys_DP0rcBsFTg     2  2009-06-16      1  UIR6A84YShz0-xe-O-LLRQ   
1850  -aaVZUYi4Ys_DP0rcBsFTg     2  2009-09-30      1  fkgwHqj83cYR39g-6SRWHw   

      stars                                               text    type  \
1834      2  I remember Country Kitchen when I was a young ...  review   
1835      3  We get takeout from CK every month or so, and ...  review   
1836      2  Have been to Nick's many times for breakfast, ...  review   
1837      1  This manager is a chauvinist pig, he has fired...  review   
1838      4  Southern hospitality? Yes ma'am (or Mister)  :...  review   
1839      4  I've been eating at this CK since they opened ...  review   
1840      4  Been here a couple of times and enjoyed it ver...  review   
1841      4  As the mom of  2 kids (a 3 year old and a 8 mo...  review   
1842      2  Despite Christine S and her stellar review, I'...  review   
1843      4  This was a great place to stop and eat breakfa...  review   
1844      1  Overpriced and boring.  There is nothing overl...  review   
1845      3  This place is OK.  Nothing really special or a...  review   
1846      3  Most of the food is good, sometimes the fish p...  review   
1847      4  Quite good for simple food. There's something ...  review   
1848      4  My wife and I have been to the Country Kitchen...  review   
1849      3  I think this is a great neighborhood place to ...  review   
1850      2  This place is great for breakfast and however ...  review   

      useful                 user_id  polarity  subjectivity  
1834       5  faaOI6hU64h6SSaF0f11eg  0.189927      0.413169  
1835       1  JYsqFExLbQ7KCBZy5VRZ6A  0.072727      0.579545  
1836       0  igx5DwIwXg6rDslEgkTeew  0.220278      0.546667  
1837       4  6EjE8BHw-z2v8mUGvn4zbg -0.187240      0.604444  
1838       5  KQMzfaaI9jfo68S4CsCifA  0.369844      0.669080  
1839       0  zbuG_wbjhyHRjlu5_YJKtg  0.104365      0.496825  
1840       1  UG4EKu13JRwzRix6ESINdg  0.487000      0.596000  
1841       1  ICyDkMNmWVJe71bV9yi3Gw  0.094667      0.587778  
1842       1  Ji9PeffxjwqPLO7pEfSpKQ  0.015448      0.586555  
1843       2  MkTaG2ledrPFimTCx8mKMQ  0.523148      0.711111  
1844       4  lpgjORUHhRVEcvPIae0pBg  0.213456      0.627128  
1845       0  UXZDRVdx8eJqdqb13Bcfcg  0.323413      0.650794  
1846       2  PkyfS1JSXBaOJTRN3bMCCA  0.175000      0.462500  
1847       1  TlMK-Ad_NLIHCX1XCwrqSw  0.350000      0.478571  
1848       3  BSaIJ5b8FdJ-UwUjnCGz3w  0.361136      0.448864  
1849       2  adJKzp-8QUCTHHSw2le3Jg  0.378030      0.528030  
1850       1  RuV3cTAii5xLFiVfszZI-g  0.425000      0.487500

In [116]:
len(df_bid)

17

In [119]:
df_bid['stars'].mean()

2.9411764705882355

## 5 and 1 Star Reviews

In [4]:
df_bin = df[(df['stars'] == 5) | (df['stars'] == 1)][['text', 'stars']]

In [5]:
df_bin['stars'] = df_bin['stars'].map(lambda x: 1 if x == 5 else 0)

In [6]:
len(df_bin)

52677

In [7]:
df_bin.index = range(len(df_bin))

In [135]:
vectorizer = TfidfVectorizer(ngram_range=(1,2), strip_accents='unicode')
vectorizer.fit(df_bin['text'])
x = vectorizer.transform(df_bin['text'])

NameError: name 'df_bin' is not defined

In [11]:
x

<540612x5847148 sparse matrix of type '<type 'numpy.float64'>'
	with 89101432 stored elements in Compressed Sparse Row format>

In [53]:
model = MultinomialNB().fit(x, df_bin['stars'])

In [73]:
testvector = vectorizer.transform(['good food bad service'])
model.predict(testvector)

array([1])

In [39]:
x_back = x.toarray()

In [40]:
df_x = pd.DataFrame(x_back, columns=vectorizer.get_feature_names())

In [44]:
df_x['never again']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
6        0.0
7        0.0
8        0.0
9        0.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       0.0
16       0.0
17       0.0
18       0.0
19       0.0
20       0.0
21       0.0
22       0.0
23       0.0
24       0.0
25       0.0
26       0.0
27       0.0
28       0.0
29       0.0
        ... 
52647    0.0
52648    0.0
52649    0.0
52650    0.0
52651    0.0
52652    0.0
52653    0.0
52654    0.0
52655    0.0
52656    0.0
52657    0.0
52658    0.0
52659    0.0
52660    0.0
52661    0.0
52662    0.0
52663    0.0
52664    0.0
52665    0.0
52666    0.0
52667    0.0
52668    0.0
52669    0.0
52670    0.0
52671    0.0
52672    0.0
52673    0.0
52674    0.0
52675    0.0
52676    0.0
Name: never again, dtype: float64

In [168]:
forests = RandomForestClassifier()
forests.fit(x, df_bin['stars'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [175]:
forestvec = vectorizer.transform(['good food bad service'])
abc.predict(forestvec)

NameError: name 'abc' is not defined

In [161]:
X_train, X_test, y_train, y_test = train_test_split(x, df_bin['stars'], test_size=0.3, stratify=df_bin['stars'])

In [81]:
%%timeit -n1 -r1
# Random Forests
forest = RandomForestClassifier()
forest_acc = cross_val_score(forest, X_train, y_train, cv=1, scoring='f1')
print(forest_acc)

[ 0.91031227  0.90340087  0.90697251  0.908728    0.89891304  0.90793536
  0.90660841  0.90048587  0.90462428  0.90925689]
1 loop, best of 1: 25min 41s per loop


In [ ]:
forest = RandomForestClassifier()
forest.fit(x, df_bin['stars'])
# ypred_for = forest.predict(X_test)

In [190]:
print("accuracy: ", sklearn.metrics.accuracy_score(y_test, ypred_for))
print("precision: ", sklearn.metrics.precision_score(y_test, ypred_for))
print("recall: ", sklearn.metrics.recall_score(y_test, ypred_for))
print("f1 score: ", sklearn.metrics.f1_score(y_test, ypred_for))

('accuracy: ', 0.82457337883959048)
('precision: ', 0.82209106239460372)
('recall: ', 0.9549461312438785)
('f1 score: ', 0.88355233348436801)


In [127]:
%%timeit -n1 -r1
# Naive Bayes
nb = MultinomialNB()
nb_acc = cross_val_score(nb, X_train, y_train, cv=10, scoring='f1')
print(nb_acc)

[ 0.82130584  0.82130584  0.82068966  0.82210708  0.82210708  0.82210708
  0.82210708  0.82210708  0.82352941  0.82210708]
1 loop, best of 1: 611 ms per loop


In [131]:
nb = MultinomialNB()
nb.fit(X_train, y_train)
a = nb.predict(X_test)

In [133]:
with open('model/forest.pkl', 'wb') as f:
    pickle.dump(forest, f, protocol=pickle.HIGHEST_PROTOCOL)

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
with open('model/vectorizer.pkl', 'wb') as f:
    pickle.dump(forest, f, protocol=pickle.HIGHEST_PROTOCOL)

In [16]:
with open('model/forest.pkl', 'rb') as f:
    forest = pickle.load(f)

In [15]:
with open('model/vectorizer.pkl', 'rb') as f:
    vectorizer = pickle.load(f)

In [20]:
forestvec = vectorizer.transform(['good food great food bad service horrible people'])
forest.predict(forestvec)

array([0])

## SQL Stuff

In [ ]:
# cnx = create_engine('postgresql://hhaq:haqckers@hh2010.me:5432/reviews')

In [105]:
conn_string = "host='hh2010.me' dbname='reviews' user='hhaq' password='haqckers'"
conn = psycopg2.connect(conn_string)

In [106]:
cur = conn.cursor()

In [107]:
cur.execute("DROP TABLE IF EXISTS yelp;")
cur.execute("CREATE TABLE yelp(Id SERIAL PRIMARY KEY, Review_Id TEXT, User_Id TEXT, Business_Id TEXT, Business_Name TEXT, Date DATE, Review TEXT, Useful SMALLINT, Funny SMALLINT, Cool SMALLINT, Stars SMALLINT, Rating SMALLINT);")
conn.commit()

In [128]:
query

'INSERT INTO yelp VALUES(\'NxL8SIC5yqOdnlXCg18IBg\',\'KpkOkG6RIf4Ra25Lhhxf1A\',\'2aFiy99vNLklCx3T_tGS9A\', \'None\',2011-10-10,"If you enjoy service by someone who is as competent as he is personable, I would recommend Corey Kaplan highly. The time he has spent here has been very productive and working with him educational and enjoyable. I hope not to need him again (though this is highly unlikely) but knowing he is there if I do is very nice. By the way, I\'m not from El Centro, CA. but Scottsdale, AZ.",0,0,0,5,0)'

In [127]:
query = "INSERT INTO yelp VALUES('" + str(d['review_id']) + "','" + str(d['user_id']) + "','" + str(d['business_id']) + "', 'None'," + str(d['date']) + ',"' + str(d['text']) + '\",' + str(d['useful']) + "," + str(d['funny']) + "," + str(d['cool']) + "," + str(d['stars']) + ",0)"

In [134]:
with open('yelp_academic_dataset_review.json') as f:
    for i in range(10):
        d = json.loads(f.readline().strip())
        ds = [d['review_id'], d['user_id'], d['business_id'], 'None', d['date'], d['text'],d['useful'], d['funny'], d['cool'], d['stars'], 0]
#         cur.executemany("""INSERT INTO yelp(Review_Id, User_Id, Business_Id) VALUES (%(review_id)s, %(user_id)s, %(business_id)s)""", d)
        query = "INSERT INTO yelp (Review_Id, User_Id, Business_Id, Business_Name, Date, Review, Useful, Funny, Cool, Stars, Rating) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"        
        cur.execute(query, ds)
        conn.commit()

In [104]:
if conn:
    conn.close()